# Generated by Django 5.0.7 on 2024-08-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
